///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesIcon = 'assets/images/icon.png';
  static const String imagesPlant = 'assets/images/plant.svg';
  static const String imagesSplashBottom = 'assets/images/splash_bottom.svg';
  static const String imagesSplashIcon = 'assets/images/splash_icon.svg';
  static const String onboardingBg = 'assets/images/onboarding_bg.svg';

}
